### ISSUE TITLE
Investigate chart sometimes throwing error

### ISSUE THREAD

**Issue by priecint** [AugurProject/augur-ui-react-components#7]
After going to market page there is sometimes `Cannot read property 'requestAnimationFrame' of undefined` error

**Comment by thinkloop** [comment]
@priecint any repro steps you know to help @stephensprinkle debug

**Comment by priecint** [comment]
This needs to be reproduced from augur repo, not AURC.

1/ use charts (I created separate branch for it https://github.com/AugurProject/augur-ui-react-components/tree/%237-chart-error)
2/ load the market page
3/ it throws [here](https://github.com/kirjs/react-highcharts/blob/master/src%2FchartsFactory.jsx#L32) (whole stack trace below).

I have feeling that this might occur due
a/ frequent updating/removing of the component
b/ something else
c/ stuff I haven't thought of

Whole stack trace:
> "TypeError: Cannot read property 'requestAnimationFrame' of undefined
    at t.renderChart (http://localhost:8080/2.0.0/build.js:3:256804)
    at t.componentDidMount (http://localhost:8080/2.0.0/build.js:3:257268)
    at r.notifyAll (http://localhost:8080/2.0.0/build.js:3:264640)
    at r.close (http://localhost:8080/2.0.0/build.js:3:381540)
    at r.closeAll (http://localhost:8080/2.0.0/build.js:3:413384)
    at r.perform (http://localhost:8080/2.0.0/build.js:3:412800)
    at s (http://localhost:8080/2.0.0/build.js:3:366554)
    at Object.batchedUpdates (http://localhost:8080/2.0.0/build.js:3:347230)
    at Object.a [as batchedUpdates] (http://localhost:8080/2.0.0/build.js:3:385313)
    at Object._renderNewRootComponent (http://localhost:8080/2.0.0/build.js:3:368206)"

**Comment by stephensprinkle** [comment]
TODO:
* Final Round of Testing
* Inclusion of dummy data in components repo (if not already present)

**Comment by stephensprinkle** [comment]
Haven’t been able to repro this issue in multiple environments.  

The inclusion of the charts on the market page is found in this PR: #17

Closing until the issue reproducibly resurfaces.
